# Generated by Django 3.2.7 on 2021-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['last_name', 'first_name', 'username'], name='account_man_last_na_6fa1a5_idx'),
        ),
    ]
