# Generated by Django 3.2.7 on 2023-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_auto_20210907_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('UNV', 'Unverified'), ('BLK', 'Blacked'), ('DEL', 'Deleted')], default='UNV', max_length=25),
        ),
    ]
